# Generated by Django 5.2 on 2025-05-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmodel',
            name='is_expired',
            field=models.BooleanField(null=True),
        ),
    ]
