# Generated by Django 5.2 on 2025-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
