# Generated by Django 5.2 on 2025-05-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_delete_customtoken_customtoken'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
            ],
            bases=('authtoken.token',),
        ),
    ]
