# Generated by Django 5.2 on 2025-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_delete_customtoken_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='expiry_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
