# Generated by Django 5.2 on 2025-05-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
