# Generated by Django 5.2 on 2025-05-21 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_customgroup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +91.....', regex='^(\\+91[\\-\\s]?|91[\\-\\s]?|0)?[6-9]\\d{9}$')]),
        ),
    ]
