# Generated by Django 5.2 on 2025-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_tempmodel_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmodel',
            name='is_expired',
            field=models.BooleanField(null=True),
        ),
    ]
