# Generated by Django 5.2 on 2025-05-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_product_categories_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Cart',
        ),
    ]
