# Generated by Django 5.2 on 2025-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_customtoken_expiry_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={'verbose_name': 'Custom Token', 'verbose_name_plural': 'Custom Tokens'},
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
