# Generated by Django 5.2 on 2025-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_tempmodel_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmodel',
            name='expiry_time',
        ),
        migrations.AlterField(
            model_name='tempmodel',
            name='is_expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
