# Generated by Django 5.2 on 2025-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_customtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expiry_time',
            field=models.IntegerField(default=50),
        ),
    ]
