# Generated by Django 5.2 on 2025-05-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_tempmodel_expiry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmodel',
            name='is_expired',
        ),
    ]
