# Generated by Django 5.2 on 2025-05-22 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_customtoken_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expiry_time',
            field=models.CharField(default=datetime.timedelta(seconds=1000)),
        ),
    ]
