# Generated by Django 5.2 on 2025-05-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_customtoken_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
