# Generated by Django 5.2 on 2025-05-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_tempmodel_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmodel',
            name='is_expired',
        ),
    ]
